# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool: MyPool

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(f62a9ff9-2aa6-487c-88c1-8f874ce9c4ce)'
    appType: 'webAppLinux'
    appName: 'etienne2024'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
